# fly.toml app configuration file generated for seed on 2023-09-11T16:10:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seed"
primary_region = "scl"

[build]
[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true

[checks]
 [checks.alive]
  type = "tcp"
  interval = "15s"
  timeout = "12s"
  grace_period = "5s"